### ISSUE TITLE
Would you like to have another backend?

### ISSUE THREAD

**Issue by wuwbobo2021** [nguyencongminh090/GomokuAI#2]
Hello. I just finished my `android-usbser-rs`, and realized that you’ve published a prototype of a new gomoku engine. However, the C++ code is written by your friend, but not yourself.

Therefore I may change my previous promise and resume the development of my new `figrid-board` in a few weeks. I’ll write it in Rust (as the first one) and a bit of OpenCL. I will transfer the ownership of my library to you.

Now I think my plan doesn't conflict with your (your friend’s) profits: it’s good to compare both backends’ performance. But if you wouldn't allow me to do so, just close this issue as **unplanned**.

**Comment by nguyencongminh090** [comment]
Hello! First of all. For non-related topic with the repo. May you write email to me? Secondly, what do you mean about another backend? Figrid-board was a third party to read Renlib file, isn't it? Don't you mean you make it as an engine to solve gomoku problem too? 
Alright, I'm starting to focus on how to write a gomoku engine. I would emphasize about language: Python code will use to brainstorm idea and then C++ will use to make main source. About Rust, I don't have enough time to learn more new language so still move it at the end.
You mentioned the C++ code that I merged? (minimax...cpp). Yes, my friend, but a real friend. I and he study at same university then I invited him to my project. For performance, I understand that it's very very bad, he just make it as a try to implement the algorithm (alphabeta, minimax, pvs, ids, ...). Look how did he write the evaluate part, terrible, seems like AI code. But, just a start, we're going to write again the Evaluator and Search part this week.
The main source now is `testBitBoard.py` I'm writing this one.
For further plan of project: currently, we're learning to use classical evaluation to understand how an engine work. Laterly, we will try to apply Machine Learning, such as CNN or NNUE model to improve the Evaluator Function.  (I have a friend learning AI too, he may help me in his level). For now, we have a group with about 4 people.
For your saying about your plan, sorry, I'm not really understand the backend you mentioned (the word "backend" itself quite abstract). But if you also write about Gomoku Engine. It's okay. We may take a look to improve our idea. There is no conflict so you're welcome.

**Comment by nguyencongminh090** [comment]
From now, you can send email to my new email: nguyenminhfptu@gmail.com
My old email are full of advertisement.

**Comment by wuwbobo2021** [comment]
Yes, I’ll make the new `figrid-board` as an engine.

Closing this issue because you think it’s a non-related topic in this repo.

Good luck to you!
